import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Turns the client's `dist/` into a JavaScript module of `type: "file"` imports.
 *
 * `bun build --compile` embeds a file it can see imported, and hands back a path
 * that `Bun.file` reads from inside the executable. It cannot embed a directory
 * it never sees named, so the import list has to be written out — and Vite's
 * filenames are content-hashed, so it has to be written out per build.
 */
const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, '..', '..', 'web', 'dist')
const out = join(here, '..', 'src', 'assets.generated.js')

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

let files: string[]
try {
  files = walk(dist).sort()
} catch {
  // No client build yet. That is the normal state in development, where Vite
  // serves the client itself and the host server only answers /api and /ws —
  // so write the empty map and let the server say "no client bundled" if
  // anyone asks it for a page.
  files = []
  console.warn(`no client build at ${dist} — writing an empty asset map`)
}

const identifier = (index: number) => `asset${index}`

const imports = files
  .map((file, index) => {
    const from = relative(join(here, '..', 'src'), file)
      .split('\\')
      .join('/')
    return `import ${identifier(index)} from '${from.startsWith('.') ? from : `./${from}`}' with { type: 'file' }`
  })
  .join('\n')

const entries = files
  .map((file, index) => {
    const route = `/${relative(dist, file).split('\\').join('/')}`
    return `  ${JSON.stringify(route)}: ${identifier(index)},`
  })
  .join('\n')

writeFileSync(
  out,
  `// Generated by \`bun run build\` (apps/host/scripts/bundle-assets.ts). Do not edit.
${imports}

export const ASSETS = {
${entries}
}
`,
)

console.log(`bundled ${files.length} client asset(s) into ${out}`)
