import { existsSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Points the build at `narration/clips.db` when `pack-narration.ts` has made
 * one, so `bun build --compile` embeds it. Without one the binary still
 * narrates, it just has no built-in piper voice.
 */
const here = dirname(fileURLToPath(import.meta.url))
const clips = join(here, '..', 'narration', 'clips.db')
const out = join(here, '..', 'src', 'narration.generated.js')

const header = '// Generated by apps/host/scripts/bundle-narration.ts. Do not edit.\n'

if (existsSync(clips)) {
  writeFileSync(
    out,
    `${header}import clips from '../narration/clips.db' with { type: 'sqlite', embed: 'true' }\n\nexport const NARRATION = clips\n`,
  )
  console.log(`bundled narration clips from ${clips}`)
} else {
  writeFileSync(out, `${header}export const NARRATION = null\n`)
}
