import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Copies espeak-ng's Emscripten glue out of `text2wav`, with the one line that
 * makes it unusable in a compiled binary removed.
 *
 * The package ends its glue by mounting the real filesystem over `/usr/share`,
 * rooted at the module's own directory, and reading its voice data back out
 * through that mount. `bun build --compile` resolves `__dirname` at build time
 * and bakes the path in, so the executable goes looking for the build machine's
 * `node_modules` and aborts on any other computer — which is the whole thing we
 * are trying to stop needing.
 *
 * So the mount goes, and `espeak-wasm.ts` writes the same files into the
 * in-memory filesystem from assets embedded in the executable instead.
 */
const here = dirname(fileURLToPath(import.meta.url))
// Resolved rather than joined: a workspace install puts the real package under
// `node_modules/.bun`, and only the resolver knows where.
const source = Bun.resolveSync('text2wav/lib/espeak-ng.js', here)
const out = join(here, '..', 'src', 'espeak.generated.js')

const MOUNT = `const path = require('path')
FS.createPath('/', 'usr/share', true, false)
FS.mount(NODEFS, {
  root: path.join(__dirname, "..")
}, '/usr/share')
Module.FS = FS`

const REPLACEMENT = `FS.createPath('/', 'usr/share', true, false)
Module.FS = FS`

const glue = readFileSync(source, 'utf8')

// Loudly, rather than writing a module that fails at the first clue of the
// night: if the package restructures this, the patch has to be looked at again.
if (!glue.includes(MOUNT)) {
  throw new Error(
    `${source} no longer ends with the filesystem mount this patch removes. ` +
      'Check what text2wav changed before updating the snippet.',
  )
}

writeFileSync(
  out,
  `// Generated by scripts/bundle-espeak.ts from text2wav. Do not edit.\n${glue.replace(MOUNT, REPLACEMENT)}`,
)
console.log(`espeak glue → ${out}`)
