// Generated by `bun run db:bundle`. Do not edit.
// Source: packages/db/drizzle — regenerate after every `drizzle-kit generate`.

export interface Migration {
  tag: string
  statements: string[]
}

export const migrations: Migration[] = [
  {
    "tag": "0000_known_nightmare",
    "statements": [
      "CREATE TABLE `app_setting` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`updated_at` integer NOT NULL\n);",
      "CREATE TABLE `buzzer_binding` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`key` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`player_id` text,\n\t`team_id` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `game_session`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`player_id`) REFERENCES `session_player`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`team_id`) REFERENCES `team`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `buzzer_binding_key_unique` ON `buzzer_binding` (`session_id`,`key`);",
      "CREATE TABLE `game` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`slug` text NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text,\n\t`min_players` integer DEFAULT 2 NOT NULL,\n\t`max_players` integer DEFAULT 12 NOT NULL,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);",
      "CREATE UNIQUE INDEX `game_slug_unique` ON `game` (`slug`);",
      "CREATE TABLE `game_pack` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`game_id` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`name` text NOT NULL,\n\t`content` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`game_id`) REFERENCES `game`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `game_pack_slug_unique` ON `game_pack` (`game_id`,`slug`);",
      "CREATE TABLE `game_session` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name` text NOT NULL,\n\t`status` text DEFAULT 'lobby' NOT NULL,\n\t`active_match_id` text,\n\t`registration_open` integer DEFAULT true NOT NULL,\n\t`narration_mode` text DEFAULT 'off' NOT NULL,\n\t`narration_rate` integer DEFAULT 95 NOT NULL,\n\t`narration_voice` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);",
      "CREATE UNIQUE INDEX `game_session_code_unique` ON `game_session` (`code`);",
      "CREATE TABLE `match` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`game_id` text NOT NULL,\n\t`pack_id` text,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`state` text DEFAULT '{}' NOT NULL,\n\t`rev` integer DEFAULT 0 NOT NULL,\n\t`started_at` integer,\n\t`ended_at` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `game_session`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`game_id`) REFERENCES `game`(`id`) ON UPDATE no action ON DELETE restrict,\n\tFOREIGN KEY (`pack_id`) REFERENCES `game_pack`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `match_session_idx` ON `match` (`session_id`);",
      "CREATE TABLE `match_event` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`match_id` text NOT NULL,\n\t`actor_player_id` text,\n\t`type` text NOT NULL,\n\t`payload` text DEFAULT '{}' NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`match_id`) REFERENCES `match`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`actor_player_id`) REFERENCES `session_player`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `match_event_match_created_idx` ON `match_event` (`match_id`,`created_at`);",
      "CREATE TABLE `narration_clip` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`engine` text NOT NULL,\n\t`voice` text,\n\t`text` text NOT NULL,\n\t`mime_type` text NOT NULL,\n\t`audio` text NOT NULL,\n\t`created_at` integer NOT NULL\n);",
      "CREATE TABLE `session_player` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`team_id` text,\n\t`token` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`score` integer DEFAULT 0 NOT NULL,\n\t`connected` integer DEFAULT true NOT NULL,\n\t`joined_at` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `game_session`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`team_id`) REFERENCES `team`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE UNIQUE INDEX `session_player_token_unique` ON `session_player` (`token`);",
      "CREATE INDEX `session_player_session_idx` ON `session_player` (`session_id`);",
      "CREATE UNIQUE INDEX `session_player_name_unique` ON `session_player` (`session_id`,`display_name`);",
      "CREATE TABLE `team` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`color` text NOT NULL,\n\t`position` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `game_session`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `team_name_unique` ON `team` (`session_id`,`name`);"
    ]
  }
]
