import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Turns the `drizzle/` folder into a TypeScript module.
 *
 * The binary has no folder to read migrations from — it is one file — so the
 * SQL has to be part of the bundle. Generating a module keeps `drizzle-kit
 * generate` as the only thing anyone has to run by hand.
 */
const here = dirname(fileURLToPath(import.meta.url))
const folder = join(here, '..', 'drizzle')
const out = join(here, '..', 'src', 'migrations.generated.ts')

interface JournalEntry {
  idx: number
  when: number
  tag: string
}

const journal = JSON.parse(readFileSync(join(folder, 'meta', '_journal.json'), 'utf8')) as {
  entries: JournalEntry[]
}

const known = new Set(readdirSync(folder).filter((name) => name.endsWith('.sql')))

const migrations = journal.entries
  .sort((a, b) => a.idx - b.idx)
  .map((entry) => {
    const file = `${entry.tag}.sql`
    if (!known.has(file)) throw new Error(`journal names ${file}, which is not in ${folder}`)
    const statements = readFileSync(join(folder, file), 'utf8')
      .split('--> statement-breakpoint')
      .map((statement) => statement.trim())
      .filter(Boolean)
    return { tag: entry.tag, statements }
  })

const body = `// Generated by \`bun run db:bundle\`. Do not edit.
// Source: packages/db/drizzle — regenerate after every \`drizzle-kit generate\`.

export interface Migration {
  tag: string
  statements: string[]
}

export const migrations: Migration[] = ${JSON.stringify(migrations, null, 2)}
`

writeFileSync(out, body)
console.log(`bundled ${migrations.length} migration(s) into ${out}`)
